# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/2i2c-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    # The sphinx-2i2c-theme requires python >= 3.8
    python: "3.8"
    nodejs: "16"
  jobs:
    post_build:
      # Use staticrypt to hide each page behind a password
      - npm install -g staticrypt
      - find _build/html/hidden -type f -name "*.html"
      - find _build/html/hidden -type f -name "*.html" -exec staticrypt {} password -o {} \;
      - cat _build/html/hidden/test.html

sphinx:
  configuration: conf.py

# Explicitly opt out of trying to build additional formats such as PDF and ePub
formats: []

python:
  install:
    - requirements: requirements.txt
