# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/2i2c-team-compass/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    # The sphinx-2i2c-theme requires python >= 3.8
    python: "3.8"
    nodejs: "16"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
