name: Update Activity Archive
description: |
  This action updates the activity archive so that cards finished in the last cycle
  are moved to an "archive" column, and cards from two cycles ago are
  "Archived" entirely (so they are not visible)
on:
  schedule:
  # Run every 1st and 15th day of the month
  - cron: "0 0 1,15 * *"

  workflow_dispatch:

jobs:
  open-sync-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r .github/requirements.txt

    - name: Post sync md
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        python scripts/archive-old-cards.py