name: Add readthedocs preview link to pull requests

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  autolink-rtd-previews:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "2i2c-team-compass"
