# From https://github.com/marketplace/actions/close-matching-issues
name: Close a weekly team sync issue
on:
  schedule:
  # Run every Tuesday a03:00PM UTC / 05:00PM Europe / 08:00AM California
  - cron: "00 15 * * 2"

jobs:
  close-sync-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/close-matching-issues@v2
        with:
          query: 'sync in:title label:"type: team-sync" is:open'
          token: ${{ secrets.GITHUB_TOKEN }}
