# From https://github.com/marketplace/actions/close-matching-issues
name: Close a weekly team sync issue
on:
  schedule:
  # Run every Saturday at 08:00 (which is Midnight California time)
  - cron: "00 08 * * 6"

jobs:
  close-sync-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/close-matching-issues@v2
        with:
          query: 'sync in:title label:"type: team-sync"'
          token: ${{ secrets.GITHUB_TOKEN }}
