name: Open issues for team coordination and work planning
on:
  schedule:
  # Run every Tuesday at 07:00 AM UTC / 09:00AM Europe / 00:00AM California
  - cron: "0 07 * * 2"

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  create-sprint-planning-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Calculate if we're on a 2-week cycle
      run: python .github/workflows/is-two-weeks.py
      id: is-two-weeks
    - name: Print variables for reference
      run: |
        echo "Days since last meeting is ${{ steps.is-two-weeks.outputs.N_DAYS_SINCE }}"
        echo "Weeks since last meeting is ${{ steps.is-two-weeks.outputs.N_WEEKS_SINCE }}"
        echo "Is-two-weeks is ${{ steps.is-two-weeks.outputs.IS_TWO_WEEKS }}"
    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    - name: Setup tmate session
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
      uses: mxschmitt/action-tmate@v3

    - name: Open a sprint planning issue
      if: ${{ steps.is-two-weeks.outputs.IS_TWO_WEEKS == 'True' }} 
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/meeting-sprint-planning.md

    - name: Open a support steward transfer issue
      if: ${{ steps.is-two-weeks.outputs.IS_TWO_WEEKS == 'True' }} 
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/support-steward.md
