name: Open a weekly team sync issue
on:
  schedule:
  # Run on the 25th day of the month so there's time to update the issue w/ info
  - cron: "0 1 26 * *"

  workflow_dispatch:

jobs:
  create-sync-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/meeting-team.md
