name: Open a support steward transfer issue
on:
  schedule:
  # Run every 1st and 15th of the month at 07:00 AM UTC / 09:00AM Europe / 00:00AM California
  - cron: "0 7 1,15 * *"

  workflow_dispatch:

jobs:
  create-sprint-planning-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/support-steward.md
