name: Open a sprint planning meeting issue
on:
  schedule:
  # Run every Wednesday at 07:00 AM UTC / 09:00AM Europe / 00:00AM California
  - cron: "0 07 * * 3"

  workflow_dispatch:

jobs:
  create-sprint-planning-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Calculate if we're on a 2-week cycle
      run: python datetime.py
      id: is-two-weeks
    - name: Open a new issue
      if: ${{ steps.is-two-weeks.IS_TWO_WEEKS == 'True' }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE/meeting-sprint-planning.md
