name: Build documentation and check links

on:
  pull_request:  # TODO: REMOVE THIS WHEN DONE PLAYING AROUND
  workflow_dispatch:
  schedule:
  # Runs at 1am each day.
  - cron: '0 1 * * *'

jobs:
  linkcheck:
    uses: 2i2c-org/.github/.github/workflows/documentation-link-check.yml@main
    with:
      docs_path: .
      # Issue: https://github.com/2i2c-org/team-compass/issues/453
      issue_number: 453
      requirements_path: requirements.txt
