name: Build documentation and check links

on:
  workflow_dispatch:
  schedule:
  # Runs at 1am each day.
  - cron: '0 1 * * *'

jobs:
  linkcheck:
    uses: 2i2c-org/.github/.github/workflows/documentation-link-check.yaml@main
    with:
      docs_path: .
      requirements_path: requirements.txt
