name: Sort our project cards based on priority label
on:
  schedule:
  # Run every day
  - cron: "0 1 * * *"

  workflow_dispatch:

jobs:
  open-sync-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r .github/requirements.txt

    - name: Sort issues
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        python scripts/sort-issues.py