# From https://github.com/JasonEtco/create-an-issue
name: Open a weekly team sync issue
on:
  schedule:
  # Run every monday at 00:00
  - cron: "0 0 * * 1"

  workflow_dispatch:

jobs:
  open-sync-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r .github/sync-requirements.txt

    - name: Post sync md
      env:
        GHAPI_TOKEN: ${{ secrets.GHAPI_TOKEN }}
      run: |
        python scripts/post-team-sync.py